server:
  port: 1070
spring:
  application:
    name: MODEL-APPLICATION
  datasource:
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5432/gravitatedb
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

