apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager-deployment
  labels:
    name: user-manager-pod
    app: user-manager-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-manager-pod
      app: user-manager-service
  template:
    metadata:
      labels:
        name: user-manager-pod
        app: user-manager-service
    spec:
      containers:
        - name: user-manager
          image: containerprince/user-management
          ports:
            - containerPort: 1071
          env:
            - name: SPRING_MAIL_HOST
              value: smtp.gmail.com
            - name: SPRING_MAIL_PORT
              value: "587"
            - name: SPRING_MAIL_USERNAME
              value: ivaanki00@gmail.com
            - name: SPRING_MAIL_PASSWORD
              value: svuegooshtkrpgsz
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: "?Mfptnj123@hview2022"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/gravitatedb
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server-service:8762/eureka