apiVersion: v1
kind: Service
metadata:
  name: user-manager-service
spec:
  selector:
    name: user-manager-pod
    app: user-manager-service
  ports:
    - port: 1071
      targetPort: 1071
      nodePort: 30007
  type: NodePort