apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-manager
  labels:
    app: content-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-manager
  template:
    metadata:
      labels:
        app: content-manager
    spec:
      containers:
        - name: content-manager
          image: content-manager:latest
          ports:
            - containerPort: 1072
          env:
            - name: JAVA_OPTS
              value: -Xmx256m -Xms256m
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8762/eureka
          readinessProbe:
            httpGet:
              path: /health
              port: 1072
          livenessProbe:
            httpGet:
              path: /health
              port: 1072
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
