apiVersion: v1
kind: Service
metadata:
  name: content-manager-service
spec:
  selector:
    name: content-manager-pod
    app: content-manager-service
  ports:
    - port: 1072
      targetPort: 1072
      nodePort: 30009
  type: NodePort