apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-manager
  labels:
    app: project-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-manager
  template:
    metadata:
      labels:
        app: project-manager
    spec:
      containers:
        - name: content-manager
          image: project-manager:latest
          ports:
            - containerPort: 1073
          env:
            - name: JAVA_OPTS
              value: -Xmx256m -Xms256m
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8762/eureka
          readinessProbe:
            httpGet:
              path: /health
              port: 1073
          livenessProbe:
            httpGet:
              path: /health
              port: 1073
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
