apiVersion: v1
kind: Service
metadata:
  name: project-manager-service
spec:
  selector:
    name: project-manager-pod
    app: project-manager-service
  ports:
    - port: 1073
      targetPort: 1073
      nodePort: 30008
  type: NodePort