apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    name: eureka-server
    app: eureka-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eureka-server
      app: eureka-server-app
  template:
    metadata:
      labels:
        name: eureka-server
        app: eureka-server-app
    spec:
      containers:
        - name: eureka-server
          image: containerprince/eureka
          ports:
            - containerPort: 8762