apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
  labels:
    name: eureka-service
    app: eureka-server-app
spec:
  selector:
    name: eureka-server
    app: eureka-server-app
  ports:
    - port: 8762
      targetPort: 8762
      nodePort: 30005
  type: NodePort