server:
  port: 1071
spring:
  application:
    name: USER-MANAGER-SERVICE-APPLICATION
  datasource:
    username: postgres
    password: ?Mfptnj123@hview2022
    url: jdbc:postgresql://localhost:5432/gravitatedb
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.model
  #Map underline style to hump style
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
    fetch-registry: true
    register-with-eureka: true