apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    name: api-gateway
    app: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api-gateway
      app: api-gateway-app
  template:
    metadata:
      labels:
        name: api-gateway
        app: api-gateway-app
    spec:
      containers:
        - name: apigw
          image: containerprince/apigw
          ports:
            - containerPort: 9192
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server-service:8762/eureka