apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    name: api-gateway-service
    app: api-gateway-app
spec:
  type: NodePort
  selector:
    name: api-gateway
    app: api-gateway-app
  ports:
    - port: 9192
      targetPort: 9192
      nodePort: 30006