name: Parallel CI

on:
  push:
    branches:
      - main
      - dev
      - ivan-manzi-ci-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [content_manager_service, gravitate_apigw, gravitate_service_registry,project_manager_service,user_manager_service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-    

      - name: Print modified projects
        run: |
          echo "Below are the projects:"
          echo "-----------------------------"
          echo "${{ matrix.project }}"

      - name: Build model module
        run: |
          cd model
          mvn clean install

      - name: Build and push Docker images
        run: |
          for project in ${{ matrix.project }}; do
            echo "Build & Push docker images"
            cd $project
            #generate jar file with dependencies
            mvn clean package spring-boot:repackage
            docker build -t containerprince/$project .
            cd ..
          done