name:  main CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - content_manager_service
          - gravitate_apigw
          - user_manager_service
          - project_manager_service
          - gravitate_service_registry
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test with Maven
        run: mvn -B verify

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Install Dependencies
        run: |
          mvn install
          cd model
          mvn install
          
      - name: Build and push Docker images
        run: |
          cd ${{ matrix.module }}
          mvn clean package spring-boot:repackage
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gravitate-apis:${{ matrix.module }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/gravitate-apis:${{ matrix.module }}
          
          
          
          
          
