name: Sequential CI

on:
  push:
    branches:
      - main
      - dev
      - ivan-manzi-ci-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [content_manager_service, gravitate_apigw, gravitate_service_registry, project_manager_service, user_manager_service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Print modified projects
        run: |
          echo "Below are the projects:"
          echo "-----------------------------"
          echo "${{ matrix.project }}"

      - name: Install maven dependencies
        run: |
          echo "Installing maven dependencies sequentially"
          for project in ${{ matrix.project }}; do
            echo "Install maven dependencies for module $project"
            cd $project
            mvn clean install
            cd ..
          done
