name:  sequential CI

on:
  push:
    branches:
      - main
      - dev
      - ivan-manzi-ci-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Find all projects
        run: |
          touch all-projects.txt
          git ls-tree -r --name-only HEAD | awk -F '/' '{print $1}' | grep -vE '^(\.github|\.gitignore|\.idea|k8s|model|docker-compose\.yml|gravitateDb\.sql|payment_management_service\.iml|pom\.xml)$' | sort | uniq > all-projects.txt
      
      - name: Print modified projects
        run: |
          echo "Below are the projects:"
          echo "-----------------------------"
          echo cat all-projects.txt
          
      - name: Install maven dependencies
        run: |
          if ! [ -s all-projects.txt ]; then
            echo "No projects found, skipping..."
            exit 0
          fi
          while read project; do
            # Check if $project is a directory
            if test -d "$project"; then
              cd $project
              mvn clean install
              cd ..
            else
              echo "$dir is not a directory, skipping..."
            fi
          done < all-projects.txt
