name: Release and Docker Build

on:
  push:
    branches:
      - main
      - dev

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PWD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - content_manager_service
          - gravitate_apigw
          - gravitate_service_registry
          - project_manager_service
          - user_manager_service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        run: |
          if [ -f "$GITHUB_WORKSPACE/$module/Dockerfile" ]; then
            echo "Dockerfile found in $module"
            docker buildx create --use
            docker buildx build --push --tag $module:${{ github.ref_slug }} $module
          else
            echo "Dockerfile not found in $module"
          fi
