name: Release and Docker Build

on:
  push:
    branches:
      - main
      - dev

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PWD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - content_manager_service
          - gravitate_apigw
          - gravitate_service_registry
          - project_manager_service
          - user_manager_service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        run: echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin

      - name: Check if module contains Dockerfile
        id: check-dockerfile
        run: |
          if [ -f "$GITHUB_WORKSPACE/$module/Dockerfile" ]; then
            echo "Dockerfile found in $module"
            echo "::set-output name=dockerfile-found::true"
          else
            echo "Dockerfile not found in $module"
            echo "::set-output name=dockerfile-found::false"
          fi

      - name: Build and Push Docker Image
        if: steps.check-dockerfile.outputs.dockerfile-found == 'true'
        run: |
          docker buildx create --use
          docker buildx build --push --tag $module:${{ github.ref_slug }} $module
