name: Release Workflow

on:
  release:
    types:
      - published
      - unpublished
      - prereleased

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: "maven"
      
      - name: Set released tag in system env vars
        run: echo "RELEASE_VERSION=${{ env.GITHUB_REF#refs/*/ }}" >> $GITHUB_ENV

      - name: Throw error when tag name is invalid
        if: ${{ !(contains(env.RELEASE_VERSION, '-dev')) && !(contains(env.RELEASE_VERSION, '-staging')) && !(contains(env.RELEASE_VERSION, '-uat')) && !(contains(env.RELEASE_VERSION, '-prod')) }}
        run: |
          echo "Invalid tag name. Tag name should end with either -dev, -staging, -uat, or -prod"
          exit 1

      - name: Print success message
        run: echo "Release workflow executed successfully."
