name: Sequential Execution

on: [push]

jobs:
  sequential_execution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Command Sequentially
        run: |
          echo "Running command sequentially"
          # Replace the following line with your actual command
          # e.g., time my_command
          sleep 3
